const MODULE_ONE = 1
const MODULE_TWO = 2
const SPACE_BAR = 32
const MENU = 1
const INTRO = 2
const INSTRUCTIONS = 3
const INGAME = 4

export {MODULE_ONE, MODULE_TWO, SPACE_BAR, MENU, INTRO, INSTRUCTIONS, INGAME}
